spring:
  application:
    name: centralisationservice
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          bootstrap: true
          uri: https://github.com/ABDELMOUIZ1/config-repo
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
