spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory-service
    username: root
    password: 0000
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 0
